# Generated by Django 4.2.25 on 2025-11-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimetres'), ('in', 'Inches')], default='cm', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds'), ('st', 'Stones')], default='kg', max_length=10),
        ),
    ]
