# Generated by Django 4.2.25 on 2025-11-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usersettings_accepted_friendship_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='default', help_text='Selected avatar icon', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exercise_privacy',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('groups', 'Groups Only'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fertility_privacy',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('groups', 'Groups Only'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='habits_privacy',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('groups', 'Groups Only'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meals_privacy',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('groups', 'Groups Only'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_privacy',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('groups', 'Groups Only'), ('public', 'Public')], default='private', max_length=20),
        ),
    ]
