# Generated by Django 4.2.25 on 2025-11-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_avatar_userprofile_exercise_privacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='habits_privacy',
        ),
    ]
