# Generated by Django 4.2.25 on 2025-12-04 10:21

from django.db import migrations


def convert_inches_to_cm(apps, schema_editor):
    """
    Convert all heights stored in inches to centimeters.
    Heights where height_unit='in' are currently stored as inches and need conversion.
    Heights where height_unit='cm' are already in cm and don't need conversion.
    """
    UserProfile = apps.get_model('users', 'UserProfile')
    
    # Get all profiles with height_unit='in' (these heights are in inches)
    profiles_in_inches = UserProfile.objects.filter(height_unit='in')
    
    for profile in profiles_in_inches:
        if profile.height:
            # Convert inches to cm (1 inch = 2.54 cm)
            profile.height = float(profile.height) * 2.54
            profile.save()
    
    print(f"Converted {profiles_in_inches.count()} heights from inches to cm")


def reverse_cm_to_inches(apps, schema_editor):
    """
    Reverse migration: convert heights back to inches for profiles that prefer inches.
    """
    UserProfile = apps.get_model('users', 'UserProfile')
    
    # Get all profiles with height_unit='in' (these should be reverted to inches)
    profiles_prefer_inches = UserProfile.objects.filter(height_unit='in')
    
    for profile in profiles_prefer_inches:
        if profile.height:
            # Convert cm back to inches (1 cm = 0.393701 inches)
            profile.height = float(profile.height) / 2.54
            profile.save()
    
    print(f"Reverted {profiles_prefer_inches.count()} heights from cm to inches")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_habits_privacy'),
    ]

    operations = [
        migrations.RunPython(convert_inches_to_cm, reverse_cm_to_inches),
    ]
