# Generated by Django 4.2.25 on 2025-11-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionlog',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
