# Generated by Django 4.2.25 on 2025-11-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='habit_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
