# Generated by Django 4.2.25 on 2025-11-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetrics',
            name='basal_metabolic_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetrics',
            name='body_fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetrics',
            name='daily_caloric_needs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetrics',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
