# Generated by Django 4.2.25 on 2025-11-03 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exercise_type', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('walking', 'Walking'), ('rowing', 'Rowing'), ('jump_rope', 'Jump Rope'), ('aerobics', 'Aerobics'), ('weightlifting', 'Weightlifting'), ('bodyweight', 'Bodyweight Exercises'), ('resistance_bands', 'Resistance Bands'), ('circuit_training', 'Circuit Training'), ('crossfit', 'CrossFit'), ('powerlifting', 'Powerlifting'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('tai_chi', 'Tai Chi'), ('other', 'Other')], max_length=100)),
                ('duration_minutes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_unit', models.CharField(blank=True, choices=[('miles', 'Miles'), ('kilometers', 'Kilometres')], max_length=20, null=True)),
                ('distance_logged', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('emoji', models.CharField(blank=True, choices=[('😀', 'Very Satisfied'), ('🙂', 'Satisfied'), ('😐', 'Neutral'), ('🙁', 'Dissatisfied'), ('😫', 'Exhausted')], max_length=2, null=True)),
                ('calories_burned', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StrengthSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exercise_name', models.CharField(max_length=100)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_sets', to='exercise.exerciselog')),
            ],
        ),
    ]
