# Generated by Django 4.2.25 on 2025-11-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='duration_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('walking', 'Walking'), ('rowing', 'Rowing'), ('jump_rope', 'Jump Rope'), ('aerobics', 'Aerobics'), ('weightlifting', 'Weightlifting'), ('bodyweight', 'Bodyweight Exercises'), ('resistance_bands', 'Resistance Bands'), ('circuit_training', 'Circuit Training'), ('crossfit', 'CrossFit'), ('powerlifting', 'Powerlifting'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('tai_chi', 'Tai Chi'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='intensity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
    ]
